# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples


# PATH=$PATH:$HOME/.nvm/nvm.sh   # Add NVM to PATH
. $HOME/.nvm/nvm.sh
cd ~/
